### ISSUE TITLE
qmlimagefilter

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#102]
We need a simple single bare bones test app for shader development (ios, Android, OS X, Linux) that doesn't require a camera. 

Having some simple image based test harness for ogles_gpgpu and related gpgpu processing will also facilitate regression testing (travis, etc).
##

**Comment by ruslo** [comment]
> We need a simple single bare bones test app for shader development

@headupinclouds without Qt?

**Comment by headupinclouds** [comment]
I think so.  Doing it without QT would allow us to have some lightweight regression tests for the gpgpu pipeline configuration tests that could run on travis easily.

**Comment by ruslo** [comment]
> Doing it without QT would allow us to have some lightweight regression tests

Well, actually I mean UI only. I think Qt still can be used for managing resources, loading image and calling OpenGL ES wrappers.

**Comment by headupinclouds** [comment]
I think I agree... mostly.  Qt does make the glue for cross platform testing much easier.  My only hesitation is due to build times, since Qt currently would prevent this from being used for practical regression testing of shaders in travis, for example.  I'm working on trying to fix the OS X ogles_gpgpu path now, and the regression testing would be very handy (of course) to check that the shaders are all still working in iOS and Android after my hacking.

**Comment by headupinclouds** [comment]
@ruslo: See initial hunter + gtest skeleton tests for ogles_gpgpu shaders (blew OS X only) in this branch:

https://github.com/headupinclouds/gatherer/blob/pr.gtest/src/tests/ogles_gpgpu/test-ogles-gpgpu.cpp

A Gtest "fixture" is configured in test-shader.cpp:

```
TEST_F(OGLESGPGPUTest, grayscale)
{
    void * pixelBuffer = image.ptr();
    bool useRawPixels = true;
    m_pipeline->captureOutput(image.size(), pixelBuffer, useRawPixels, 0, GL_BGRA);

    cv::Mat result(image.size(), CV_8UC4);
    m_pipeline->getOutputData(result.ptr());

    // TODO: compare result with expected ground truth result

    cv::imshow("result", result);
    m_context->swapBuffers();
    cv::waitKey(2000);
}
```

This is reusing the GLContext class for an initial OS X + glew implementation.  We'll want to add expected shader output for each shader in ogles_gpgpu so we can add gtest assertions (within some tolerance).  As you pointed out previously, we can use QT to provide the cross platform OpenGL context initialization.  (Ideally we can do this without opening a window.)

```
 "/Users/dhirvonen/devel/gatherer/assets/images/lena512color.png"
1: Test timeout computed to be: 9.99988e+06
1: [==========] Running 1 test from 1 test case.
1: [----------] Global test environment set-up.
1: [----------] 1 test from OGLESGPGPUTest
1: [ RUN      ] OGLESGPGPUTest.grayscale
1: OpenGL version: 2.1 NVIDIA-10.4.2 310.41.35f01
1: GLSL version: 1.20
1: Vendor: NVIDIA Corporation
1: Renderer: NVIDIA GeForce GT 650M OpenGL Engine
1: camera frames are of size 512x512 (aspect 1.000000)
1: [       OK ] OGLESGPGPUTest.grayscale (3244 ms)
1: [----------] 1 test from OGLESGPGPUTest (3244 ms total)
1:
1: [----------] Global test environment tear-down
1: [==========] 1 test from 1 test case ran. (3244 ms total)
1: [  PASSED  ] 1 test.
1/1 Test #1: TestOGLESGPGP ....................   Passed    3.29 sec
```

**Comment by headupinclouds** [comment]
see #127 (separate console app version for command line might still be good)

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
