### ISSUE TITLE
relwithdebinfo + QT problem

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#105]
If I add a full set of Xcode configurations like this:
`set(CMAKE_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")`

I'm not able to run qmlvideofilter with the `relwithdebinfo` configuration:

```
make: /Users/dhirvonen/devel/gatherer/_builds/ios-9-1-arm64/src/3rdparty/ogles_gpgpu/ogles_gpgpu/CMakeScripts/ogles_gpgpu_automoc_cmakeRulesBuildPhase.makeRelWithDebInfo: No such file or directory
make: *** No rule to make target `/Users/dhirvonen/devel/gatherer/_builds/ios-9-1-arm64/src/3rdparty/ogles_gpgpu/ogles_gpgpu/CMakeScripts/ogles_gpgpu_automoc_cmakeRulesBuildPhase.makeRelWithDebInfo'.  Stop.
```

**Comment by ruslo** [comment]
Problem is about ogles_gpgpu subproject set `CMAKE_CONFIGURATION_TYPES` to `Release;Debug`. Fixes:
- https://github.com/headupinclouds/ogles_gpgpu/pull/11
- https://github.com/headupinclouds/gatherer/pull/107

**Comment by headupinclouds** [comment]
Thanks for the fix.
