### ISSUE TITLE
android/ios application launch options

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#108]
Provide a convenient way to list available targets and a way to launch them easily from the command line (autocomplete, etc).  For now I've provided some notes describing the `build.py ... --target` and `launch_apk.sh` options in the wiki:

https://github.com/headupinclouds/gatherer/wiki/Android-Application-Launch-Notes

This might be addressed by some of the `polly` configuration file extensions.

**Comment by ruslo** [comment]
> This might be addressed by some of the polly configuration file extensions

Yes, that's a job for Polly.

Some notes:

> Provide a convenient way to list available targets

As far as I know it can't be done in a cross-platform way since there is no such option in CMake. Though some generators can do this. E.g. in `Makefile` you can run target `help` to see list of all targets. For Polly it will be `--target help`. Also general peculiarity is that you need to generate project first and only then you will able to access the list of all targets.

> a way to launch them easily from the command line

We already have launch targets for Android, you can run `--target qmlvideofilter-launch` to launch `qmlvideofilter` from command line on device.

**Comment by headupinclouds** [comment]
Does `qmlvideofilter-launch` correspond to `QtApp-release-unsigned.apk`?  Both the `QtApp-debug.apk` and `QtApp-release-unsigned.apk` versions seem to be built at the same time (regardless of config mode).

```
_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release/src/app/qmlvideofilter//bin/QtApp-debug-unaligned.apk
_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release/src/app/qmlvideofilter//bin/QtApp-debug-unaligned.apk.d
_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release/src/app/qmlvideofilter//bin/QtApp-debug.apk
_builds/android-ndk-r10e-api-19-armeabi-v7a-neon-Release/src/app/qmlvideofilter//bin/QtApp-release-unsigned.apk
```

**Comment by ruslo** [comment]
> Both the QtApp-debug.apk and QtApp-release-unsigned.apk versions seem to be built at the same time (regardless of config mode).

At least C++ code has different flags and `*.cpp` files compiled only once. `QtApp-release-unsigned.apk` I don't see this file if build type is `Debug`.

> Does qmlvideofilter-launch correspond to QtApp-release-unsigned.apk?

Don't see where `QtApp` cames from, probably from `androiddeployqt` utility.

**Comment by ruslo** [comment]
So as a general note all this stuff cames from this fork: https://github.com/LaurentGomila/qt-android-cmake. I've just made some refactoring and check that it's working. I can investigate what's happening more deeply if needed.

**Comment by headupinclouds** [comment]
The polly <name>-launch target is working well.  Closing for now.
