### ISSUE TITLE
qmlvideofilter: Display QVideoFilterRunnable metadata in QML (object detection, etc)

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#111]
Add some dummy QML rectangle output in the qmlvideofilter app VideoFilterRunnable class as described below.  For now this can be a fixed rectangle with a std::string label to imitate an object detector that might run inside the filter.

http://doc.qt.io/qt-5/qvideofilterrunnable.html

"Filters that want to expose the results of their computation to Javascript code in QML can declare their own custom signals in the QAbstractVideoFilter subclass to indicate the completion of the operation. For filters that only calculate some results and do not modify the video frame, it is also possible to operate asynchronously. They can queue the necessary operations using the compute API and return from this function without emitting any signals. The signal indicating the completion is then emitted only when the compute API indicates that the operations were done and the results are available. Note that it is strongly recommended to represent the filter's output data as a separate instance of QJSValue or a QObject-derived class which is passed as a parameter to the signal and becomes exposed to the Javascript engine. In case of QObject the ownership of this object is controlled by the standard QML rules: if it has no parent, ownership is transferred to the Javascript engine, otherwise it stays with the emitter."

**Comment by ruslo** [comment]
Fixed

**Comment by headupinclouds** [comment]
Before closing this one out, it would be useful to add rectangle drawing on the VideoOutput preview from C++ code in the VideoFilter object.  The width, height and position will be generated within the VideoFilter code but can be fixed values in a member variable for now.

**Comment by ruslo** [comment]
> add rectangle drawing on the VideoOutput preview from C++ code in the VideoFilter object

Fixed in https://github.com/headupinclouds/gatherer/pull/119, closing
