### ISSUE TITLE
Travis timeout fix/workaround

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#116]
Travis is still failing.  There is some recent discussion about this on the hunter forum as well as the long term binary package option.  Leaving this here for discussion.

**Comment by ruslo** [comment]
Relates: https://github.com/headupinclouds/gatherer/issues/43

**Comment by headupinclouds** [comment]
Thanks to @ruslo's QT+ hunter binary cache updates, this is all building in travis now.  Appveyor is still a TODO.  iOS is still a todo.

Here is a link to the hunter notes on uploading binaries to the server when new architectures are required: https://github.com/ruslo/hunter/wiki/Uploading-binaries-to-server.  

I'll close this and create a new issue for iOS.
