### ISSUE TITLE
travis build checks

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#12]
Once OS x, iOS and android pieces are in place

**Comment by ruslo** [comment]
Optimization: build patched CMake and pack

**Comment by ruslo** [comment]
> Optimization: build patched CMake and pack

Binary release: https://github.com/ruslo/CMake/releases/tag/v3.3.2-p0
Usage example: https://github.com/forexample/hunter-simple/blob/macosx/.travis.yml

**Comment by ruslo** [comment]
Qt build time: https://github.com/ruslo/hunter/issues/247

**Comment by ruslo** [comment]
Fixed: https://travis-ci.org/headupinclouds/gatherer/builds/83782137

**Comment by ruslo** [comment]
Multi-OS check: https://github.com/headupinclouds/gatherer/issues/43
