### ISSUE TITLE
Qt QML performance, declarative-camera

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#120]
Test `declarative-camera` vs `ogles_gpgpu` performance (no shaders).

TODO (iOS + Android):
- Add FPS to `declarative-camera` target
- Add FPS to `ogles_gpgpu` (see https://github.com/headupinclouds/gatherer/issues/61)
- Check CPU usage
- Check resolutions
- Check front/back camera

**Comment by headupinclouds** [comment]
Closing.
