### ISSUE TITLE
gtest for ogles_gpgpu shader regression testing

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#123]
##

**Comment by headupinclouds** [comment]
related: #102

**Comment by headupinclouds** [comment]
Some notes on configuring "surfaceless" offscreen rendering (or hiding the surface)

http://stackoverflow.com/a/19934540/5724090

**Comment by headupinclouds** [comment]
see #127

**Comment by ruslo** [comment]
> see #127
- We can use `file(DOWNLOAD)` command to download images to avoid storing them in git history. Not a problem for small images, may be important for big. Also if there is any big collection that change from time to time then it can be organized into Hunter package
- To store resource in iOS bundle Qt tools can be used, example
  - QRC file: https://github.com/forexample/qt-cmake/blob/87aa515e24f95b01c93be3d11921486be7147d08/TextFinder/TextFinder.qrc
  - Access: https://github.com/forexample/qt-cmake/blob/87aa515e24f95b01c93be3d11921486be7147d08/TextFinder/TextFinder.cpp#L23

**Comment by headupinclouds** [comment]
@ruslo : Nice.  I'll leave this open for now so we can pursue something like the above for a cleaner solution while we fill out the shader ground truth tests (there is currently only 1 BGR->grayscale test).

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
