### ISSUE TITLE
cloud mobile device testing

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#131]
@ruslo: Adding the link you shared here: https://aws.amazon.com/device-farm/device-list/
##

**Comment by ruslo** [comment]
Just a thought aloud: I think Travis CI has no real iOS devices support so it means we have to start some custom server like Jenkins. And Hunter will work perfectly on Jenkins, there will be no need to implement "upload/server with binaries" feature.

**Comment by headupinclouds** [comment]
git samples for the device farm:

https://github.com/awslabs/aws-device-farm-sample-app-for-android

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
