### ISSUE TITLE
2d/3d graphics package

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#134]
We need a flexible lightweight framework for portable 2D (and later 3D) graphics using OpenGL (ES).  Gatherer graphics and core processing should both be decoupled from QT and LGPL license restrictions.  I don't currently see any better alternative for the UI components, however.  This should run on Android, iOS, Windows, Linux and OS X.

This one seems promising:

https://github.com/gameplay3d/GamePlay

TODO: add other packages here
##

**Comment by ruslo** [comment]
Related Hunter request: https://github.com/ruslo/hunter/issues/188

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
