### ISSUE TITLE
Qt Android Error

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#137]
https://groups.google.com/forum/#!topic/android-qt/N3wI5SpP5zM

"I found that the problem does not appear when using the gcc 4.8 toolchain it works. The problem only appears with the gcc 4.9 toolchain"

```
E/dalvikvm(14713): dlopen("/data/data/qmlvideofiler.qt/lib/libQt5Qml.so") failed: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "libQt5Qml.so"...
```
##

**Comment by headupinclouds** [comment]
gatherer is retired, closing.

**Comment by kevinlq** [comment]
Hello, I also encountered the same mistake, how do you solve it?
