### ISSUE TITLE
travis builds w/ asset deployment

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#139]
Leverage the new Hunter binary cache feature to get the end-to-end gatherer builds (qmlvideofilter, etc) running on Travis (these were previously exceeding Travis timeouts).  As a first step, we can create the required builds and upload the Qt binary package from a host machine as needed, then find some way to automate this for "one step" multi-platform builds at a later time.

The first set of platforms can include:
- xcode
- android-ndk-r10e-api-19-armeabi-v7a-neon 
- ios-9-2-hid
- linux (not critical, libcxx?)

Use CPack to bundle and deploy per build assets on github.

Ideally, a final step on the host machine will collect all deployed assets and bundle these in a multi-os + toolchain tree layout.  

Once this is working, we can add Appveyor.  Some packages (ogles_gpgpu) will need to be updated for Windows.

Note: android-ndk-r10e-api-16-armeabi-v7a-neon-clang-35-hid would be good, but can use android-ndk-r10e-api-19-armeabi-v7a-neon if Qt builds are still failing with this toolchain.

**Comment by ruslo** [comment]
> xcode

This toolchain use default `Xcode` in system. If we switch to `osx-10-9` I think we can share Travis CI environment with local. Need to test.

**Comment by ruslo** [comment]
> If we switch to osx-10-9 I think we can share Travis CI environment with local. Need to test.

Yep, matches. `osx-10-9` produce `2ab6082` on both Travis environment and my local machine.

**Comment by headupinclouds** [comment]
:+1:

**Comment by ruslo** [comment]
[TODO] test old experiments with Linux:

```
-qt-xkbcommon-x11
-no-fontconfig # https://bugreports.qt.io/browse/QTBUG-51738
```

```
# Disable 3rd party from system
list(APPEND configure_opts "-qt-freetype")
list(APPEND configure_opts "-qt-harfbuzz")
list(APPEND configure_opts "-qt-libjpeg")
list(APPEND configure_opts "-qt-libpng")
list(APPEND configure_opts "-qt-pcre")
list(APPEND configure_opts "-qt-zlib")
```

**Comment by ruslo** [comment]
`osx-10-9` toolchain success:
- https://travis-ci.org/ingenue/hunter/jobs/117931357

**Comment by ruslo** [comment]
> osx-10-9 toolchain success

Building simple Qt application using Hunter cache from server:
- https://travis-ci.org/forexample/qt-cmake/builds/118026340

Release with uploaded `*.dmg` installers:
- https://github.com/forexample/qt-cmake/releases/tag/v1.2.654

**Comment by ruslo** [comment]
`cereal` is broken on Android:
- https://travis-ci.org/ingenue/hunter/jobs/118219414

not used in Gatherer in fact

**Comment by ruslo** [comment]
`libyuv` uploaded:
- https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=libyuv

**Comment by ruslo** [comment]
`cereal` done:
- https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=cereal

**Comment by headupinclouds** [comment]
> cereal is broken on Android:

i have some project level fixes for this using local definitions of c++ routines that are missing in android.  i can add this to the test.

**Comment by ruslo** [comment]
Just for your information I've updated Hunter uploading script so it can retry upload on failure several times. But it doesn't help with uploading of huge size file (900 MB archive of Android SDK: https://github.com/ingenue/hunter-cache/releases/download/cache/948d85477ed5fe9c9a015062ec0031ef1dcfb4b2.tar.bz2). This file was uploaded manually using web-form after 3 attemps.

Another problem that I've mentioned before is that we run out of available disk space on Travis OSX:
`System Error: No space left on device`.

Currently Android stuff is about 6 GB of files after unpacking (3 GB for NDK and 3 GB for SDK), this is like installing OS :)

I have a few ideas about optimization of sizes of both NDK and SDK. Planning to investigate possibilities.

**Comment by ruslo** [comment]
> we run out of available disk space on Travis OSX

May be helpful (at least will not hurt):
- https://github.com/travis-ci/travis-ci/issues/5820

**Comment by ruslo** [comment]
I've made a test:
- https://travis-ci.org/travis-ci-tester/travis-test-env/jobs/118772422

Summary:
- 10537184 KB (~10 GB) available after installation of Python. This is a point of start of build scripts (without NDK/SDK if test is Android)
- 10637356 KB (~10 GB) available after `brew cleanup` (100172 KB removed ~ 97 MB)
- 11072572 KB (~10 GB) available after `rm -rf ${BREW_CACHE_DIR}` (535388 KB total removed ~ 522 MB)

> May be helpful

Doesn't make any significant changes in context of the current problem.

**Comment by ruslo** [comment]
Script for creating minimal NDK: https://github.com/hunter-packages/android-ndk

Results:

```
Original sizes: archive 382.92 MB, unpacked 2.88 GB
Pruned sizes: archive 96.75 MB, unpacked 291.24 MB
```

(4 times smaller archive to download, 10 times smaller disk space when unpacked)

Testing Polly now:
- https://travis-ci.org/ruslo/polly/builds/119633764

**Comment by ruslo** [comment]
> Testing Polly now

Works fine, merged to master: https://travis-ci.org/ruslo/polly/builds/119633764

Now will see how SDK can be minimized.

**Comment by ruslo** [comment]
Pruning of NDK/SDK helps.

Uploaded Android works for both OSX and Linux:
- https://travis-ci.org/ingenue/hunter/builds/120148156

Note: have to build Qt Android twice (for OSX and Linux) since Qt depends on [Android-SDK](https://github.com/ruslo/hunter/blob/a4f5110af859e0b6e667be58501c19937d6fa208/cmake/projects/Qt/schemes/url_sha1_qt.cmake.in#L105), `Android-SDK` depends on [Android-Build-Tools](https://github.com/hunter-packages/android-sdk/blob/0afd87d2744bdd116d5bb9cca0c5b7433364815c/CMakeLists.txt#L108) and `Android-Builds-Tools` differs for [OSX and Linux](https://github.com/ruslo/hunter/blob/a4f5110af859e0b6e667be58501c19937d6fa208/cmake/projects/Android-Build-Tools/hunter.cmake)

**Comment by ruslo** [comment]
> ios-9-2-hid

For now C++ flags from toolchain doesn't pass to Qt build as far as I remember, so this with result same binaries as `ios-9-2`. Also does `hid` matters for static libraries? Plus we should exclude `armv7s` because of this bug: https://bugreports.qt.io/browse/QTBUG-48805

**Comment by ruslo** [comment]
> linux

Need to try docker. Will search for ready images or will create new and share for future experiments.

**Comment by ruslo** [comment]
iOS Qt success:
- https://travis-ci.org/ingenue/hunter/jobs/120104475

**Comment by ruslo** [comment]
> Need to try docker

Finally I've managed that. I can't upload local image to Docker Hub (looks like it's too big). I've found https://quay.io service that allow me to build image remotely.
- Hunter wiki: https://github.com/ruslo/hunter/wiki/Uploading-binaries-to-server#environment-notes
- Image creating instructions (not needed, just for your information): https://github.com/hunter-packages/travis-linux-docker

**Comment by headupinclouds** [comment]
Updated symbol list:
- IOS_TOOLCHAIN; host=OS X (NOTE: QT bug requires exclusion of armv7s)
- osx-10-9; host=OS X
- android-ndk-r10e-api-19-armeabi-v7a-neon; host={OS X, Ubuntu}
- gcc-4-8; host=Ubuntu 12.04 LTS (NOTE: Travis default is Ubuntu 12.04, need docker for other variants, such as Cent OS, etc)

=== IOS_TOOLCHAIN Notes ===
The travis images impose some restrictions on which ios toolchains are available (see below)
ios-8-1 : operative ios toolchain for current travis multi-arch (OS X + LInux/Ubuntu 12.04 LTS) image
ios-9-2 : desired ios toolchain (possible using current default single-arch travis image

TODO:
- .travis.yml : The build + asset deployment is working for all of the above in isolated tests (thanks to the hunter Qt binary cache timeout workaround).  To get the end-to-end build for all architectures/toolchains in gatherer, we just need to update the .travis.yml file.
- sample script/command to trigger the full build and asset deployment for all architectures, which is probably just committing and pushing a tag to the gatherer repository
- final script (bash/python) on host machine to poll for successful travis build + asset deployment, with a final download and merge/tar for a target host OS (this could possibly be done with CPack as well)
- the travis builds require the qt binary cache uploads, which are currently in an experimental branch, so the end-to-end build must use this experimental hunter branch.

**Comment by ruslo** [comment]
> >  linux
> 
> Need to try docker

Fresh article:
- https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/manage_docker

I see powershell commands, Windows support docker now? (note: as far as I know it was only possible to run **Linux** VM on Windows before)

TODO: try it

**Comment by ruslo** [comment]
After adding xcb and X11 packages to Hunter Linux works:
- https://travis-ci.org/ingenue/hunter/jobs/122010732

> host=Ubuntu 12.04 LTS (NOTE: Travis default is Ubuntu 12.04, need docker for other variants, such as Cent OS, etc)

Since final executable linked statically and doesn't depends on system xcb/X11 I think there is a high probability that it will work for other Ubuntu variants or Cent OS as well. I will create branch `hunter.linux` in https://github.com/forexample/qt-cmake and pack executable for future experiments.

**Comment by ruslo** [comment]
> it will work for other Ubuntu variants or Cent OS as well

Yep, looks like it's working. Release for Linux:
- https://github.com/forexample/qt-cmake/releases/tag/v2.13.42

Download/unpack archive and run TextFinder - works OK for Ubuntu 12.04, Ubuntu 14.04, Cent OS 7.

I have some problems with fonts, similar to:
- http://stackoverflow.com/questions/20751604

but it's deployment issue, not about compatibility.

**Comment by ruslo** [comment]
qtbase for osx toolchains uploaded:
- https://travis-ci.org/ingenue/hunter/builds/123329124

**Comment by ruslo** [comment]
qtbase for linux + osx done:
- https://travis-ci.org/ingenue/hunter/builds/123727320

**Comment by ruslo** [comment]
OpenGL needed for `qtdeclarative` to work. I've tried to add `mesa` to Hunter, added several dependencies and hit some issues. For now I've paused this approach and decide to use system one. It may lead to Linux incompatibility:
- CentOS GL location: `/usr/lib64/libGL.so`
- Ubuntu GL location: `/usr/lib/x86_64-linux-gnu/libGL.so`

so at least library paths conflicts. In future I guess "hunterizing" mesa may be a solution.

**Comment by headupinclouds** [comment]
I think using the system libs is the right approach.  To my mind, building OpenGL from source seems to be overkill.

**Comment by ruslo** [comment]
> To my mind, building OpenGL from source seems to be overkill

Usual dilemma - the hard and correct way vs easy and faulty way. Since location of `libGL.so` not saved in `toolchain-id` (hence not in cache meta info) both versions of Qt will conflict. On practice I can predict that different compiler version will be used on Ubuntu and CentOS so `toolchain-id` will differs, effectively masking this problem.

**Comment by ruslo** [comment]
>  ios-9-2 : desired ios toolchain (possible using current default single-arch travis image

See #150

**Comment by ruslo** [comment]
> just committing and pushing a tag to the gatherer repository

See #151

**Comment by ruslo** [comment]
> final script (bash/python) on host machine to poll for successful travis build + asset deployment, with a final download and merge/tar for a target host OS

Do I understand this part correctly? Issue #152

**Comment by headupinclouds** [comment]
> Do I understand this part correctly? Issue #152

Yes.

**Comment by ruslo** [comment]
So this one seems to be fixed in general.
