### ISSUE TITLE
Camera iOS, QTMultimedia compilation fails

### ISSUE THREAD

**Issue by ghost** [headupinclouds/gatherer#143]
Hi David,

Hope you are all well !

Qtmultimedia cannot compile, and triggers the following error:

```
avfmediaassetwriter.mm:94:9: error: 'm_writerQueue' is unavailable
        m_writerQueue = writerQueue;
        ^
./avfmediaassetwriter.h:83:29: note: declaration uses __weak, but ARC is disabled
    __weak dispatch_queue_t m_writerQueue;
                            ^
avfmediaassetwriter.mm:96:9: error: 'm_delegateQueue' is unavailable
        m_delegateQueue = delegateQueue;
        ^
./avfmediaassetwriter.h:87:29: note: declaration uses __weak, but ARC is disabled
    __weak dispatch_queue_t m_delegateQueue;
                            ^
avfmediaassetwriter.mm:200:24: error: 'm_delegateQueue' is unavailable
        dispatch_async(m_delegateQueue, ^{
                       ^
./avfmediaassetwriter.h:87:29: note: declaration uses __weak, but ARC is disabled
    __weak dispatch_queue_t m_delegateQueue;
                            ^
avfmediaassetwriter.mm:224:20: error: 'm_delegateQueue' is unavailable
    dispatch_async(m_delegateQueue, ^{
                   ^
./avfmediaassetwriter.h:87:29: note: declaration uses __weak, but ARC is disabled
    __weak dispatch_queue_t m_delegateQueue;
                            ^
avfmediaassetwriter.mm:318:24: error: 'm_writerQueue' is unavailable
        dispatch_async(m_writerQueue, ^{
                       ^
./avfmediaassetwriter.h:83:29: note: declaration uses __weak, but ARC is disabled
    __weak dispatch_queue_t m_writerQueue;
                            ^
avfmediaassetwriter.mm:322:24: error: 'm_writerQueue' is unavailable
        dispatch_async(m_writerQueue, ^{
                       ^
./avfmediaassetwriter.h:83:29: note: declaration uses __weak, but ARC is disabled
    __weak dispatch_queue_t m_writerQueue;
                            ^
./avfmediaassetwriter.h:83:29: error: cannot create __weak reference in file using manual reference counting
    __weak dispatch_queue_t m_writerQueue;
                            ^
./avfmediaassetwriter.h:87:29: error: cannot create __weak reference in file using manual reference counting
    __weak dispatch_queue_t m_delegateQueue;
```

Any idea how to solve it ? Shall I change the Qt version in the hunter config file ?

Toolchain=ios-9-3-arm64
Sdk=9.3
Platform=Xcode

Cheers,
Luc Michalski

**Comment by headupinclouds** [comment]
I haven't tried `ios-9-3-arm64`, but I can try it out on my macbook.  I know there have been a few Qt toolchain incompatibility issues before.  I believe both `ios-9-1` and `ios-9-2` have been working.  I'll let you know what I see.

UPDATE: Actually I will have to upgrade to Xcode 7.3 to try this.

**Comment by ruslo** [comment]
>  I believe both ios-9-1 and ios-9-2 have been working

`armv7s` is not working, use `ios-*-wo-armv7s`

**Comment by ghost** [comment]
Hi Ruslan,

Hope you are doing well and congrats for Hunter/Polly as it is really cool and promising !

I removed armv7s from the ios-9-3.cmake file when I tried to compile:

```
set(IPHONEOS_ARCHS armv7;arm64)
set(IPHONESIMULATOR_ARCHS i386;x86_64)
```

I tried also the qt-ios-examples (https://github.com/forexample/qt-ios-examples/) and had the same problem for building qtdeclarative and qtmultimedia.

Cheers,
Luc

**Comment by ruslo** [comment]
> I tried also the qt-ios-examples

I haven't tried `9.3` toolchain yet, so there is a chance that Qt is simply broken. I see `ios-8-4` in README so it should work. Can you try it just to be sure?

**Comment by headupinclouds** [comment]
@lucmichalski : Are you familiar with objective-C?  These errors all seem to stem from ARC being disabled, which seems strange, since I believe that is usually the default in most modern objective-C.  My sense is that could be fairly straightforward fix.

```
./avfmediaassetwriter.h:83:29: note: declaration uses __weak, but ARC is disabled
```

If you are building with polly, you should be able to read through your build log in`gatherer/_logs/polly`.  

This bug report seems to be on the mark: [QTBUG-52671](https://bugreports.qt.io/browse/QTBUG-52671)

UPDATE: Which turns out to be a @ruslo post. ;)  Somehow most of my CMake+ google searches seem to end up leading back to @ruslo.

**Comment by ruslo** [comment]
Just for your information:
- https://bugreports.qt.io/browse/QTBUG-48805

Looks like it's not only `armv7s` error, will do more testing.

Note: it's about Qt 5.6, so may be not related

**Comment by ghost** [comment]
Hi guys,

Hope you are doing well !

I fixed by changing "avfmediaassetwriter.h" :

```
    // Queue to write sample buffers:
    __weak dispatch_queue_t m_writerQueue;

    QT_PREPEND_NAMESPACE(AVFScopedPointer)<AVAssetWriter> m_assetWriter;
    // Delegate's queue.
    __weak dispatch_queue_t m_delegateQueue;
```

by

```
    // Queue to write sample buffers:
    __unsafe_unretained dispatch_queue_t m_writerQueue;

    QT_PREPEND_NAMESPACE(AVFScopedPointer)<AVAssetWriter> m_assetWriter;
    // Delegate's queue.
    __unsafe_unretained dispatch_queue_t m_delegateQueue;
```

Cheers,
Luc

**Comment by ruslo** [comment]
@lucmichalski please send pull request to [Qt fork](https://github.com/hunter-packages/Qt) against branch [hunter-5.5.1-cvpixelbuffer-2](https://github.com/hunter-packages/Qt/tree/hunter-5.5.1-cvpixelbuffer-2). Feel free to mention this patch in [bug #48805](https://bugreports.qt.io/browse/QTBUG-48805), probably it should be accepted upstream too. Also note that I have same error with `5.6` but not with `5.5.1` (see my comments in [bug #488805](https://bugreports.qt.io/browse/QTBUG-48805)), are you sure you're using `5.5.1` in Hunter?

**Comment by ghost** [comment]
Yes, 5.5.1 but I have a custom version of gatherer in the pipe ^^

More precisely v5.5.1-cvpixelbuffer-2-p6

The same issuer happens with 5.6 and 5.7 beta, I tried...

I have my flight back to Europe tomorrow, as I am leaving NYC, so I ll be more proactive, after my landing. :-)

**Comment by ruslo** [comment]
> I fixed by changing "avfmediaassetwriter.h"

I've just found out that the bug that was mentioned by @headupinclouds is fixed already. 

Here is the patch:
- https://codereview.qt-project.org/#/c/156246/2

Applied to hunterized fork:
- https://github.com/hunter-packages/Qt/commit/d3929747fb63446af394df288e6cbbfc5c35621e

Qt release:
- https://github.com/hunter-packages/Qt/releases/tag/v5.5.1-cvpixelbuffer-2-p7

Hunter with new Qt version:
- https://github.com/ruslo/hunter/releases/tag/v0.14.17

> I have my flight back to

Currently I'm in process of moving too so will not be able to test new Qt version for iOS/OSX platforms. @lucmichalski Please report if it's working for you.

**Comment by ruslo** [comment]
Works fine for me:
- Hunter: https://github.com/ruslo/hunter/releases/tag/v0.14.19
- Xcode 7.3.1
- iOS 9.3.1

See pull request: https://github.com/headupinclouds/gatherer/pull/149

**Comment by ghost** [comment]
Just to confirm that I was able to compile both apps with the same environment.

Will make new tests tomorrow with new features.
