### ISSUE TITLE
gatherer goals

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#146]
This is a continuation of some broader discussion in #145. 

I think there are a number of open issues that would benefit from some discussion, including: project structure, internal + external libraries/modules, and longer term goals. There is some value in having a few different cross platform computer vision demos based on the current qmlvideofilter sample.  I'll take a stab at refactoring some of the boilerplate code in there so it can be shared between a few simple real time computer vision apps that require a basic pipeline: video -> gpu -> (processing) -> simple display.  
##

**Comment by ghost** [comment]
Hi David,

Hope you are doing well !

I made a suggestion in the Hunter's repo **suggesting to add or merge a PhoneGap Hybrid App** with the gatherer project. (Link: https://github.com/ruslo/hunter/issues/410)

Also, I am testing to make **a custom version with the following libs**:
- Find-Object (Inverted Visual Search)
- CMT (2D tracking)
- Aruco (2D tracking)
- RGBD_SLAM (Visual Odometry)
- ORB_SLAM2 (Visual Odometry)
- NanoMSG (Distributed Requests)
- LibMill (Coroutines in C)

**Goals:**
- Make distributed queries to several 2D/3D tracking libs
- Add an inverted visual dictionary for image matching
- Distributed Requests with Coroutines in C, or the Surveyor/Respondent pattern from NanoMsg
- Optimize Memory usage and Battery consumption (Avoiding Matrices copy,...) 

**Missing:**
- Core Game Engine for adding 3D objects in scene

Cheers,
Luc

**Comment by headupinclouds** [comment]
These would be great additions. 

> - CMT (2D tracking)

I'm also interested in CMT.  Do you have any experience with these implementations? 
- https://github.com/gnebehay/CMT
- https://github.com/gnebehay/CppMT

Perhaps we can create a hunter issue for one?

FWIW, hunter has a few modern tracking algorithms:
- `opencv_contrib` (available in hunter) comes with a few fairly modern [tracking algorithms](http://docs.opencv.org/3.0-beta/modules/tracking/doc/tracker_algorithms.html)
- `ccv` also has a [TLD implementation](http://libccv.org/post/ccv-now-has-a-state-of-art-tracking-algorithm)
- `dlib` has an implementation of the winning algorithm from the 2015 Visual Object Tracking Challenge (apparently acronymless) [Accurate scale estimation for robust visual tracking](http://blog.dlib.net/2015/02/dlib-1813-released.html)

> - Core Game Engine for adding 3D objects in scene

Currently there is an open issue for Urho3D in hunter. See https://github.com/ruslo/hunter/issues/389#issuecomment-220229123.  @fire has been working on that and I was able to use his current branch successfully on OS X (there are still some issues with Windows and libcxx toolchains).  That project is complex enough that it would benefit from another pair of eyes.  Which platform(s) do you use for development?

> Distributed Requests with Coroutines in C, or the Surveyor/Respondent pattern from NanoMsg

Qt seems to have a nice event system, but I do like the idea of relying on Qt only for the bare minimal device + IO abstraction (camera interface, etc) and UI components due to LGPL restrictions, such that any application could be easily moved to a different UI.  I haven't seen NanoMsg and will take a look.

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
