### ISSUE TITLE
Upload artifacts on new git tag

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#151]
Every push of release tag should trigger uploading of artifacts.

See for example: https://github.com/forexample/github-binary-release

Block: issue #139 
##

**Comment by ruslo** [comment]
@headupinclouds David, can you please test this feature - create new tag and push it:

``` bash
> git tag v0.0.1
> git push --tags
```

**Comment by headupinclouds** [comment]
@ruslo: I get a build error related to Qt.

https://travis-ci.org/headupinclouds/gatherer/jobs/137687264#L828-L834

**Comment by ruslo** [comment]
> I get a build error related to Qt

Actually this is kind of GitHub issue. GitHub server does return code `22` after Hunter try to access cache meta information. Usually this code mean that there is no such file, but this file exists. Log example:
- https://travis-ci.org/headupinclouds/gatherer/jobs/137811027

quote:

```
-- [hunter ] Downloading file (try #0 of 10):
-- [hunter ]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/8c15f91/Android-SDK/0.0.3/d2abf69/da39a3e/d41f56c/da39a3e/f8c81e1/CACHE.DONE
-- [hunter ]   -> /home/travis/.hunter/_Base/Cache/meta/8c15f91/Android-SDK/0.0.3/d2abf69/da39a3e/d41f56c/da39a3e/f8c81e1/CACHE.DONE
-- [hunter ] File not found
```

link to this file:
- https://raw.githubusercontent.com/ingenue/hunter-cache/master/8c15f91/Android-SDK/0.0.3/d2abf69/da39a3e/d41f56c/da39a3e/f8c81e1/CACHE.DONE
- https://github.com/ingenue/hunter-cache/blob/master/8c15f91/Android-SDK/0.0.3/d2abf69/da39a3e/d41f56c/da39a3e/f8c81e1/CACHE.DONE

Need to improve Hunter logic here. Need to try several times (let it be twice for now).

**Comment by ruslo** [comment]
Ok, fix applied. Works fine now. Have a problem with iOS 9.3 toolchain. Will open pull request after fix.

**Comment by ruslo** [comment]
> @headupinclouds David, can you please test this feature - create new tag and push it

@headupinclouds Can you try it again please

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
