### ISSUE TITLE
Script to fuse artifacts

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#152]
Final script to merge all artifacts from different toolchains into one archive. I guess this will be some Python script that will be run by user from local machine since all CI builds run in independent fashion . AppVeyor and Travis are different services so otherwise there need some third party service to trigger (or run) merge job.

Block #139 
##

**Comment by ruslo** [comment]
Okay, now we have something to experiment with:
- https://github.com/ruslo/gatherer/releases/tag/v0.0.3

Linux and OSX Android artifacts in fact contains same files, so until there will be no host tools installed for Android toolchain we can use one archive for both hosts. iOS contains armv7 arm64 binaries: armv7s break Qt, simulator's i386 and x86_64 break Gatherer. OSX's libcxx and osx-10-9 differs only by version of compilers and minimum OSX deployment version (libcxx use default, osx-10-9 set to 10.9).

@headupinclouds What layout expected? Do we need Release/Debug variants fused or in separate archives?

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
