### ISSUE TITLE
Android build errors

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#16]
I've pushed android branch: https://github.com/ruslo/gatherer/tree/android

But got next compiler errors:

```
In file included from /.../gatherer/src/app/preview-qt/glwidget.cpp:41:0:
/.../gatherer/src/app/preview-qt/glwidget.h:124:10: error: 'mutex' in namespace 'std' does not name a type
     std::mutex m_mutex;
```

Looks like gcc from Android NDK is not fresh enough to support some of c++11 features.

@headupinclouds Do you know toolchains that support it?

**Comment by headupinclouds** [comment]
I know android toolchains frequently require more #includes than iOS.  I
will try to take a look, but it might be as simple as adding:

#include <mutex>

**Comment by ruslo** [comment]
> but it might be as simple as adding

Heh, your are right :)

**Comment by ruslo** [comment]
Fixed: https://github.com/headupinclouds/gatherer/pull/18
