### ISSUE TITLE
ndk c++ opencv android camera does not work

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#19]
see: http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk#Use-native-camera-in-your-NDK-project-C

We need CV_CAP_ANDROID for camera id (at least):

```
cv::VideoCapture capture(CV_CAP_ANDROID + 0);
//cv::VideoCapture capture(CV_CAP_ANDROID + 1);//front camera for Android 2.3.3 or newer

if( !capture.isOpened() )
    return;

capture.set(CV_CAP_PROP_FRAME_WIDTH, 640);
capture.set(CV_CAP_PROP_FRAME_HEIGHT, 480);

for(int i=0; i < 100; ++i)
{
    cv::Mat frame;

    capture >> frame;
    if( !frame.empty() )
        yourfunction::processFrame(frame);
}
```

That page mentions the following cmake code, but after some searching I believe this was only for < 3.0.0 releases of opencv.

```
if (COMMAND COPY_NATIVE_CAMERA_LIBS)
  COPY_NATIVE_CAMERA_LIBS(${PROJECT_NAME})
endif()
```

It also states "Warning: Native camera from OpenCV does not work inside console applications." 

This answers.opencv.org post clarifies the above comment.  For the QT APK file I think we just need to add camera permissions to the Android manifest and it should work.

http://answers.opencv.org/question/8551/use-native-opencv-c-camera-in-jni-call/?answer=8588#post-id-8588

1)cv::VideoCapture does not work in simple console application, because it has no rights to access camera. Console application does not have its own manifest and cannot allow access to camera stack.
2) cv::VideoCapture works ok in Java code with JNI calls. Do not forget add camera access permissions to Android Manifest.

It looks like this is done in qt with PACKAGE_SOURCES https://github.com/LaurentGomila/qt-android-cmake#package_sources

```
add_qt_android_apk(my_app_apk my_app
    PACKAGE_SOURCES ${CMAKE_CURRENT_LIST_DIR}/my-android-sources
)
```

With Android.manifest.xml entries like this:

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
```

As shown in the ogles_gpgpu android test:

```
https://github.com/internaut/ogles_gpgpu/blob/master/examples/android/OGVideoProcDroid/AndroidManifest.xml#L11
```

**Comment by ruslo** [comment]
> I believe this was only for < 3.0.0

Yep, I don't see any `COPY_NATIVE_CAMERA_LIBS` in 3.0.0+ version

**Comment by headupinclouds** [comment]
I will pull and try it.  The native access is provided via undocumented interfaces and isn't universal.  There is a list pointed to in the link here: http://answers.opencv.org/question/6827/android-ndk-level-access-to-camera-video-streampixels/?answer=6828#post-id-6828.

I'm not sure if this is a phone specific compatibility issue or if it is something we are doing wrong, but adding a java interface might be okay.  We can use the a C++ JNI interface or possibly skip that since I think we can send the frames to the GPU from java and then access the texture from native code.  This may require some experimentation to see what is fastest and most flexible.

If a phone isn't supported we could try building a custom native interface. 

http://code.opencv.org/projects/opencv/wiki/Building_OpenCV4Android_from_trunk#Advanced-build-your-camera-wrapper

That obviously isn't scalable.  Depending on what the native java camera overhead is, we can also try using a java => gpu texture => cpu (as needed) pipeline.

**Comment by headupinclouds** [comment]
Here is a nice thread on implementing java native camera access.  Presumably OpenCV is doing something similar.  At some point I can move these links out of the issue into a wiki.  But it is a useful collection for now.

http://www.chaonis.com/2011/09/camera-android-part-1/

**Comment by headupinclouds** [comment]
@ruslo : I just noticed this related post in my inbox from an OpenCV maintainer.

https://github.com/Itseez/opencv/issues/5374#issuecomment-141995879

"Native camera support was dropped in 3.0, because there are no important benefits on modern Android devices"

So a C++ API for the Android camera may be perfectly adequate, especially in a gpgpu pipeline.  Maybe this is already available in OpenCV?  I wanted to post this here, but won't have time to follow up for at least a few days.

**Comment by headupinclouds** [comment]
Closing since this is deprecated.  We can create a jni c++ interface to the standard Android camera (and the Camera2 interface for Android 5.0.0.)

**Comment by andriy-gerasika** [comment]
@headupinclouds
So, have you managed to create high-perf native Android camera access for Drishti, or is QtMultimedia's camera recommended choice?
Is ogles_gpgpu/examples/android/OGVideoProcDroid somewhat related to this?

**Comment by headupinclouds** [comment]
> So, have you managed to create high-perf native Android camera access for Drishti, or is QtMultimedia's camera recommended choice?

Related: https://github.com/elucideye/drishti/issues/573

Currently only the `facefilter` demo app is using the QML camera stuff.  It is a workable option for simple camera applications that are using Qt (of course), but the interface is somewhat limited (only a handful of the camera options are supported).  I would really like to see a high performance flexible mobile native (pure C++) camera interface supporting both iOS and Android as a standalone hunter package -- maybe with some generic V4L2 support to cover Raspberry Pi, or basic desktop use.  I cobbled together something quickly to abstract the video I/O in drishti example applications in the `drishti::videoio` application library, but it needs more work.

Here is an AVFoundation wrapper that should support Video on iOS and Android, for example: 

https://github.com/elucideye/drishti/blob/500ca090d44f7a8637712d4638e12ae218365e37/src/app/videoio/VideoSourceApple.h#L27

I grabbed the classes from here https://github.com/SheffieldKevin/VideoSample:
* https://github.com/elucideye/drishti/blob/master/src/app/videoio/MIMovieVideoSampleAccessor.h
* https://github.com/elucideye/drishti/blob/master/src/app/videoio/MICMSampleBuffer.h

I'd like to:
* do another github search to make sure something like this doesn't already exist
* clean up the interface
* add a generic name
* move this stuff to an external project, maybe hunter-packages/mobilecam or similar
* add a native (pure C++) Android Camera 2.0 interface (API >= 24)

I believe the android-ndk repository has some sample code for this:
* https://github.com/googlesamples/android-ndk/tree/master/camera
* https://github.com/googlesamples/android-ndk/pull/356

Perhaps these should just subclass `cv::VideoCapture`.  The code could also be added to OpenCV, but I tend to prefer a small lightweight lib that can be updated independently from OpenCV releases.  I would be inclined to use `cv::Mat` primitives, although I suppose custom generic image types might support a wider audience.  Do you have time and interest in collaborating?

**Comment by headupinclouds** [comment]
> Is ogles_gpgpu/examples/android/OGVideoProcDroid somewhat related to this

That is a sample project from Markus Konrad, which is pure Android/Java.  I'm not an Android developer, so I'd like to construct a simple, lightweight, C++ oriented, write-it-once-and-build-everywhere boilerplate application (without the Qt build overhead) using a small generic camera interface (`minicam` or whatever) and some application framework such as `SFML` (current preference (see open hunter issue https://github.com/ruslo/hunter/pull/1129)), or maybe some kind of wrapper around `glfm` and `glfw`, to support basic mobile prototyping.

**Comment by headupinclouds** [comment]
BTW, I'll probably close or freeze this project.
