### ISSUE TITLE
Logging library

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#22]
- Try g3log: https://github.com/ruslo/hunter/issues/225

**Comment by headupinclouds** [comment]
More choices:

http://www.quora.com/Whats-the-best-logger-for-C++

https://github.com/SergiusTheBest/plog

**Comment by ruslo** [comment]
To summarize requirements:
- Platforms: iOS, Android, Linux, OSX, Windows
- Thread-safe
- Print time, thread-id
- Severity (INFO, WARNING, ERROR)

Optionally:
- Custom sinks (e.g. on Android log to both __android_log, std::cout and file simultaneously)

**Comment by headupinclouds** [comment]
That looks like a good spec.  
Linux: Yes
OS X: Yes
Windows: Yes
Custom sinks: If possible

**Comment by ruslo** [comment]
> That looks like a good spec.  

Ok, updated

**Comment by ruslo** [comment]
> http://www.quora.com/Whats-the-best-logger-for-C++

I.e.:
- [log4cxx](http://logging.apache.org/log4cxx/)
- [log4cpp](http://log4cpp.sourceforge.net/)
- [spdlog](https://github.com/gabime/spdlog)
- [plog](https://github.com/SergiusTheBest/plog)

**Comment by ruslo** [comment]
g3log doesn't work on Android too: https://github.com/KjellKod/g3log/issues/32

**Comment by ruslo** [comment]
> log4cxx

Doesn't use CMake. I can't find an instructions of configuring for Android. Though looks like it works, see http://stackoverflow.com/questions/13493516. According to the Hunter Android scheme (https://github.com/ruslo/hunter/blob/5a2dbf3f15c5dc7b613efd38e12bea24bdd601a9/cmake/modules/hunter_autotools_project.cmake#L205) we should start with `--host=arm-linux-androideabi` but result is an error:

```
checking build system type... Invalid configuration `arm-linux-androideabi': system `androideabi' not recognized
```

**Comment by ruslo** [comment]
> log4cpp

quite the same

**Comment by headupinclouds** [comment]
Is the problem with glog that the CMake port doesn't compile for Android?
Begin a google project, I would expect the code itself would run on Android.

**Comment by ruslo** [comment]
> Is the problem with glog that the CMake port doesn't compile for Android?

I think it's general issue, see: https://github.com/google/glog/issues/59

**Comment by ruslo** [comment]
spdlog available in Hunter: https://github.com/ruslo/hunter/issues/232

**Comment by headupinclouds** [comment]
Closing this with merge of #29
