### ISSUE TITLE
opencv ios world build fails to find ZLIB::lib and PNG::png

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#25]
In the current develop branch, running

./bin/build-ios-8-4-for-8-0.sh 

results in the following opencv build failure.

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: ZLIB::zlib-NOTFOUND (No such file or directory)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: PNG::png-NOTFOUND (No such file or directory)

**Comment by ruslo** [comment]
@headupinclouds Looks like `cmake/modules` directory is missing. Probably it's not under git control.

**Comment by ruslo** [comment]
@headupinclouds By the way there is no need to use `configure_file(cmake/Hunter/config.cmake ...)` trick to pass variables. Now you can use `list(APPEND CMAKE_MODULE_PATH ...)`.

**Comment by headupinclouds** [comment]
Thanks. Just added.  (The travis build stuff (borrowed from hunter) is not
yet working.)  Clearly needed!

**Comment by ruslo** [comment]
> Clearly needed!

Hunter `jenkins.py` script is quite complex (in create `hunter.tar.gz` archive to test project from `examples`). There is a simplier scenario: https://github.com/forexample/hunter-simple/blob/macosx/.travis.yml

**Comment by ruslo** [comment]
Fixed in branch `develop` of Hunter: https://github.com/ruslo/hunter/commit/a3d73cee768f27c721369a9603d74834784a7074
