### ISSUE TITLE
Need VideoCamera interface abstraction

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#36]
We need to abstract camera input in a (possibly very simple) gatherer/camera library.  This interface should support two sinks: (1) images (cv::Mat) and (2) textures (opengl GLuint); and _possibly_ (3) OpenCL buffers.  Note that (1) and (3) are currently supported by cv::VideoCapture on supported platforms.  The OpenCV Android native camera support is deprecated and currently spotty on recent phones (at best), but seems to work on Windows, OS X, and Linux.  The iOS camera seems to work but OpenCL is not supported on that platform.

~~QT seems to support camera access on iOS and Android platforms~~ Moved to https://github.com/headupinclouds/gatherer/issues/42

And may provide one option, but we shouldn't be dependent upon that.

I see a few initial options:
1. VideoCaptureCV : basically cv::VideoCapture + OpenGL ES texture output (on some platforms this might be possible through use of cv::UMat (OpenCL) output with OpenCL => OpenGL conversion, except on iOS 
2. VideoCaptureAndroid: JNI interface provided by something like: gles_gpgpu/examples/android/OGVideoProcDroid/src/ogles_gpgpu/examples/ogvideoprocdroid/CamActivity.java; ogles_gpgpu/examples/android/OGVideoProcDroid/jni/og_jni_wrapper.cpp and the 
3. VideoCaptureiOS: abstraction of ogles_gpgpu/examples/ios/OGLESGPGPUVideoCam/OGLESGPGPUVideoCam/RootViewController.h
4. VideoCaptureQT: abstraction of the QT camera input
##

**Comment by ruslo** [comment]
To test on Android (call Java from C++): https://community.kde.org/Necessitas/JNI

**Comment by headupinclouds** [comment]
Relevant: https://github.com/Itseez/opencv/pull/5470

**Comment by headupinclouds** [comment]
Necessities looks good.  Here is an existence proof of android camera access in QT through necessities: http://mkk.ekk.pl/?wpis=4#.Vhh9BLRWAqY

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
