### ISSUE TITLE
ogles_gpgpu android sample improvements 

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#39]
- Project cleanups, including camera worker thread
- ~~Add a Hunter + CMake build option if this can be done cleanly.  We can at least start with a CMake build of JNI.  These changes will help with eventual abstraction and integration in a gatherer camera lib.~~ moved to https://github.com/headupinclouds/gatherer/issues/40
- Pending Android 5.0.0 updates, add a ogles_gpgpu sample https://github.com/googlesamples/android-Camera2Basic/blob/master/Application/src/main/java/com/example/android/camera2basic/Camera2BasicFragment.java
  See issues in ogles_gpgpu gatherer submodule (need links)

**Comment by ruslo** [comment]
Can't set two milestones :)

**Comment by ruslo** [comment]
Link: https://github.com/headupinclouds/ogles_gpgpu/issues/3

**Comment by ruslo** [comment]
> Project cleanups, including camera worker thread

Fixed by: https://github.com/headupinclouds/ogles_gpgpu/pull/7

**Comment by headupinclouds** [comment]
qt + qml samples are working, closing this
