### ISSUE TITLE
Travis multi-OS checks

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#43]
Linux/OSX can be tested on Travis simultaneously.

@headupinclouds Looks like multi-OS feature propagated to forks: https://travis-ci.org/ruslo/gatherer/builds/83773611. So I need to investigate possibility of creating {toolchain x configuration} matrix separately for Linux and OSX. In case if there is no such functionality need to implement workaround by `build.py` script.

**Comment by ruslo** [comment]
By the way we can use [appveyor](http://www.appveyor.com/) for Windows.

**Comment by headupinclouds** [comment]
@ruslo : It seems travis is working with the exception of iOS.  Can I close this one?  I'm trying to consolidate some issues.

I see #150, but am not sure I understand the issue completely.

**Comment by ruslo** [comment]
> Can I close this one?

I think yes.

> I see #150, but am not sure I understand the issue completely

This issue is about using iOS 9.3 toolchain. There is another issue about iOS: we don't have `ios-*-wo-armv7s` in cache. They are independent issues.

**Comment by headupinclouds** [comment]
Thanks.
