### ISSUE TITLE
Qt QML + C++ Android camera

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#44]
Investigate possibilities.
- http://doc.qt.io/qt-5/qtmultimedia-declarative-camera-photopreview-qml.html
- http://doc.qt.io/qt-5/qtqml-cppintegration-topic.html

**Comment by ruslo** [comment]
Simple QML Android example added: https://github.com/forexample/android-cmake#examples

**Comment by ruslo** [comment]
> Simple QML Android example added: https://github.com/forexample/android-cmake#examples

Same link, QML camera added.

**Comment by ruslo** [comment]
Code with error message `Failed to create video device input`: https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/plugins/avfoundation/camera/avfcamerasession.mm#L346

**Comment by ruslo** [comment]
iOS example from tutorial with QML and C++:
- https://github.com/forexample/qt-ios-examples/tree/master/qml-custom-property-types

Branch `develop` from Hunter should be used

**Comment by ruslo** [comment]
iOS declarative camera example [fixed](https://github.com/forexample/qt-ios-examples/commit/6312846f25e0129a238ce9770c10ba6ea6026150) by setting deployment target to `7.0`. Both examples should work (it's qml examples, no C++ code):
- Android https://github.com/forexample/android-cmake/tree/master/08-declarative-camera
- iOS https://github.com/forexample/qt-ios-examples/tree/master/declarative-camera

**Comment by ruslo** [comment]
Filter Qt example: https://github.com/hunter-packages/Qt/tree/hunter-5.5.1/qtmultimedia/examples/multimedia/video/qmlvideofilter_opencl

**Comment by ruslo** [comment]
SO: http://stackoverflow.com/questions/28041741/qt-qml-camera-to-c-qimage-on-android

**Comment by headupinclouds** [comment]
> > Filter Qt example: https://github.com/hunter-packages/Qt/tree/hunter-5.5.1/qtmultimedia/examples/multimedia/video/qmlvideofilter_opencl

That is a gem.  Nice find!  The opengl<->OpenCL interop was on my wish list.

**Comment by ruslo** [comment]
Just found this example:
- http://doc.qt.io/qt-5/qtmultimedia-video-qmlvideofx-example.html

might be interesting too (?) layout looks ugly on phones but okay for iPad. Non-hunter version works on my iOS devices and Android API 19 device. Have no video from camera on Android API 21 device.

**Comment by headupinclouds** [comment]
Definitely interesting.  This largely seems to have the functionality of the cross platform GPUImage we're looking for.  The description says it also demonstrates the QML <-> C++ part:

```
It also shows how native code can be combined with QML
```

I think it makes sense to get this running in Hunter, and then we can slowly swap out the QT/QML shaders with the C++ SDK we are planning (ogles_gpgpu, etc)

**Comment by ruslo** [comment]
> The description says it also demonstrates the QML <-> C++ part

From the brief look I see quite small usage of C++, even shaders loaded from files, e.g.:
- https://github.com/hunter-packages/Qt/blob/hunter-5.5.1/qtmultimedia/examples/multimedia/video/qmlvideofx/shaders/wobble.fsh

**Comment by headupinclouds** [comment]
Yeah, I see that too... just a frame rate calculation.  Seems to be there
as a HOWTO sample.

**Comment by ruslo** [comment]
Anyway want to add `qmlvideofilter_opencl` example first.

Current question: What is a way to add OpenCL to iOS?
Found this OS post: http://stackoverflow.com/questions/18847255/is-available-opencl-on-ios
So we should link private framework and add headers manually? (like from https://github.com/linusyang/opencl-test-ios/tree/master/include/OpenCL).

**Comment by headupinclouds** [comment]
No.  Unfortunately there is no official OpenCL support in iOS. Apple has their own Metal API.  Unfortunately this means OpenCL isn't portable for mobile development, whereas OpenGL shaders should run just about everywhere (although they aren't quite as flexible).

**Comment by ruslo** [comment]
Branch `pr.videofilter` created. Currently example compiles on iOS and Android. Android crashes. iOS doesn't work as I expect. For now filtering is an only convertion from QVideoFrame -> OpenGL texture -> QVideoFrame so I expecting no changes when filter is on, however no video present (if I just return `*input` or disable filtering camera works fine).

Method `VideoFilterRunnable::run`: https://github.com/headupinclouds/gatherer/blob/11a850b872ddf19b219b7ba5a9dbb875276a9896/src/app/qmlvideofilter/VideoFilterRunnable.cpp#L57

**Comment by ruslo** [comment]
> Just found this example: http://doc.qt.io/qt-5/qtmultimedia-video-qmlvideofx-example.html

Moved to separate issue: https://github.com/headupinclouds/gatherer/issues/78

**Comment by ruslo** [comment]
Okay, seems it works now. I have fix in local branch, will send it after https://github.com/headupinclouds/gatherer/pull/95 merge to avoid conflicts.

**Comment by ruslo** [comment]
Fixed by https://github.com/headupinclouds/gatherer/pull/100, epic! :)
