### ISSUE TITLE
"camera_test" runtime error

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#47]
Error `Could not open camera`:
- iOS 9.1
- iOS 9.0
- iOS 8.4
- Android API 19

**Comment by headupinclouds** [comment]
the qt qml camera interface is more stable.  closing.

**Comment by ruslo** [comment]
> the qt qml camera interface is more stable. closing.

@headupinclouds should we remove this example? update table? https://github.com/headupinclouds/gatherer/wiki/Status

**Comment by headupinclouds** [comment]
It is probably just adding clutter.  Let's drop it.

**Comment by ruslo** [comment]
> It is probably just adding clutter. Let's drop it.

Okay, will send PR. What about other targets? Can you create a list of items that should be removed from code/table: https://github.com/headupinclouds/gatherer/wiki/Status

**Comment by headupinclouds** [comment]
> What about other targets?

We probably can drop some.  qmlvideofilter is probably the only essential
one at this point.  Most of the others were stepping stones.  I'll review
these later this week when I get some time.

**Comment by ruslo** [comment]
Ok, I've created issue: https://github.com/headupinclouds/gatherer/issues/97
