### ISSUE TITLE
"preview-qt" runtime error

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#49]
- iOS 9.1
- iOS 9.0
- iOS 8.4

Assertion failed:
- https://github.com/headupinclouds/gatherer/blob/637d2bce9b45f36dc1fab9a041f9de8d329742f6/src/app/preview-qt/VideoCapture.cpp#L63

**Comment by headupinclouds** [comment]
the qt qml camera interface is more stable.  closing.
