### ISSUE TITLE
Fix "declarative-camera" building for libcxx toolchain

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#55]
Openning this issue for the record

**Comment by headupinclouds** [comment]
@ruslo : I hit a similar problem.  I'll leave it in this issue in case it is related.

This is using the top level quick build script: `./bin/build-libcxx.sh 1` (until polly configuration file extensions...)

```
-- Configuring done
CMake Error at src/app/qmlvideofilter/CMakeLists.txt:78 (add_executable):
  Target "qmlvideofilter" links to target "Qt5::QMultimediaDeclarativeModule"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

CMake Error at src/app/qmlvideofilter/CMakeLists.txt:78 (add_executable):
  Target "qmlvideofilter" links to target "Qt5::QmlQtQuick2Plugin" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

Is this a missing find_package() in the top level CMakeLists.txt QT section:
https://github.com/headupinclouds/gatherer/blob/videofilter/CMakeLists.txt#L55

Or is this more of a hunter/QT issue?

I get the same error for `./bin/build-xcode.sh 1`.  

UPDATE: libcxx build is working, but getting a runtime error #98

**Comment by headupinclouds** [comment]
Although declarative-camera is now replaced by qmlvideofilter.  Testing libcxx toolchain now.

**Comment by headupinclouds** [comment]
libcxx builds and qmlvideofilter runs in the latest.  closing.
