### ISSUE TITLE
iOS declarative-camera example with different devices

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#57]
### iPad 2, iOS 9.0.2

|  |  |
| --- | --- |
| ios-8-4-armv7 | **ok** |
| ios-9-0-armv7 | **ok** |
| ios-9-0-dep-7-0-armv7 | **ok** |

To see this error in console you should touch `Back Camera`/`Front Camera` button. To diagnose need to add extra error message here: https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/plugins/avfoundation/camera/avfcamerasession.mm#L346
### iPhone 4S, iOS 9.1

|  |  |
| --- | --- |
| ios-8-4-armv7 | **ok** |
| ios-9-0-armv7 | Cannot run on device because of `Could not find Developer Disk Image` |
| ios-9-0-dep-7-0-armv7 | Cannot run on device because of `Could not find Developer Disk Image` |
| ios-9-1-armv7 | **ok** |

`Could not find Developer Disk Image` may be caused because of incompatibility of Xcode 7.0 with iOS 9.0 and Xcode 7.1 with iOS 9.1. Though it looks strange that iOS 8.4 works. Possible solution that can be tried is to load somehow iOS 9.0 SDK to Xcode 7.1 and create new type of toolchain.
### iPhone 5S, iOS 9.1

|  |  |
| --- | --- |
| ios-9-1-arm64 | **error**: Failed to create video device input |

**Comment by ruslo** [comment]
@headupinclouds Let me know what is your experience.

**Comment by headupinclouds** [comment]
@ruslo: I tried this example on my iPhone 5s running iOS 9.1 and could see the buttons, but no video.  Same thing for both still and video mode.  Switching the camera does produce the error message you reported above: `Failed to create video device input`

**Comment by ruslo** [comment]
`I tried this example on my iPhone 5s running iOS 9.1 w/ Xcode 7.1` thanks, tables updated

**Comment by ruslo** [comment]
> Failed to create video device input

Seems that problems is about asking user about a permission to use camera. Some fields in `info.plist` are missing and iOS failed to do that and decide to deny access. Will test it more and send patches today.

**Comment by ruslo** [comment]
> Will test it more and send patches today

See: https://github.com/headupinclouds/gatherer/pull/60

Table updated.

**Comment by ruslo** [comment]
Fixed by https://github.com/headupinclouds/gatherer/pull/60
