### ISSUE TITLE
iOS ogles_gpgpu add fps

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#61]
From what I see performance is quite the same. For accurate measure need to add resolution/fps values in logs (ui widget?).

[Targets](https://github.com/headupinclouds/gatherer/wiki/Status):
- `OGLESGPGPUVideoCam`

**Comment by headupinclouds** [comment]
closing, since qmlvideofilter is display frame rate and is using olges_gpgpu

**Comment by ruslo** [comment]
@headupinclouds Actually I was thinking we need to add fps widget to `OGLESGPGPUVideoCam` example and compare it with `qmlvideofilter` (?)
