### ISSUE TITLE
Qt dynamic framework

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#64]
Build Qt as a dynamic framework on iOS for LGPL distribution
##

**Comment by ruslo** [comment]
I've just tried to build Qt with `-shared` flag and it doesn't produce dynamic libraries :(
Looks like it's a bug: https://bugreports.qt.io/browse/QTBUG-42937

So the only way to do it is to install static libraries and make some "magic"...

**Comment by ruslo** [comment]
Some quotes about LGPL.

There is no need to open your sources, you can provide object code:
- http://multinc.com/2009/08/24/compatibility-between-the-iphone-app-store-and-the-lgpl/

```
You can keep your app closed-source, but you provide to your users all the object code of
your application necessary to re-link your application.  That means for example all
the .o and .a files.  Most people forget that this option is in fact available to iPhone app developers.
```

And here is quote that you have to provide sources:
- http://wiki.qt.io/Licensing-talk-about-mobile-platforms#Qt_for_iOS

```
Camp 2 means: You have to provide the source code of your app.
```

**Comment by headupinclouds** [comment]
> So the only way to do it is to install static libraries and make some "magic"...

@ruslo: What exactly did you have in mind? ;)  

If this doesn't seem to be solvable Im thinking of removing this from the milestone, but leaving the issue open.  Thoughts?  I would guess the dynamic library build will be fixed at some point in the future.

**Comment by ruslo** [comment]
> I would guess the dynamic library build will be fixed at some point in the future

I've made a few small fixes but still got some errors, will continue investigation.

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
