### ISSUE TITLE
Necessitas

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#66]
- https://necessitas.kde.org/index.php

Needed only if there are problems with the QT camera:
- Qt camera is slow
- Qt camera interface falls out of date (i.e., Android Camera 2 framework not supported)

Some links:
- http://mkk.ekk.pl/?wpis=4#.VlCIdL98ufx

**Comment by headupinclouds** [comment]
Qt camera has been working well.  Closing for now.
