### ISSUE TITLE
Boost.compute

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#67]
[Boost.compute](https://github.com/boostorg/compute) could be adopted as a package/framework for future OpenCL extensions, once the basic (portable) OpenGL pipeline is in place.

**Comment by ruslo** [comment]
I've added this package to Hunter. I've tested it locally on my Linux machine. Travis CI for OSX works fine:
- https://travis-ci.org/ingenue/hunter/builds/108011707

Travis CI for Linux doesn't work, see comments in this commit:
- https://github.com/ingenue/hunter/commit/2ee115201ef6bf145b816031279c1fe44d61c3fc

AppVeyor windows don't work. probably need to figure out how to install OpenCL there (or use Hunter?).

**Comment by headupinclouds** [comment]
I'm looking forward to trying this (probably this weekend).  Let's get a hello world test integrated in the qmlvideofilter test application before closing this.  This could run a CMake platform check for OpenCL (most non iOS platforms) followed by some simple frame statistics in the qmlvideofilter app using boost.compute (mean, etc).  This would at least demonstrate the OpenGL <-> OpenCL interop and would be a good segue into using more interesting OpenCL kernels in array.fire.  In most vision pipelines, the core work will still be performed by portable OpenGL ES shaders (I've starting to migrate some key shaders from GPUImage to ogles_gpgpu) with additional processing that doesn't fit in the shader model being performed with OpenCL and later Apple's Metal (TODO).

**Comment by ruslo** [comment]
Just for your information looks like my mac-mini doesn't support OpenCL :(
- https://support.apple.com/en-us/HT202823

```
Mac mini (Mid 2011)     Intel HD 3000   3.3     N/A
```

Simple example return CPU device:

```
> ./_testing/_builds/gcc-Release/foo 
hello from Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
```

**Comment by headupinclouds** [comment]
Simple examples are working on os x.  Closing and may revisit this later in context of mobile device use.
