### ISSUE TITLE
Try Qt 5.6.0-beta with qmlvideofilter example

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#76]
##

**Comment by ruslo** [comment]
I've applied some fixes:
- https://github.com/hunter-packages/QtCMakeExtra/commit/9d2bb82fec411129f684fb5bc40cb03abbf035be
- https://github.com/hunter-packages/QtCMakeExtra/commit/db0f91c8f31935ecf3f59e4fe4f5843343a2151f

but got linker errors about `main`. Seems that [qtmn](https://github.com/ruslo/hunter/wiki/pkg.qt#pitfalls) trick no longer working. Looks like behaviour changed in this version. Unbelievable...

**Comment by ruslo** [comment]
Working now, no need to test 5.6 version. Will keep it open since fix needed in future. Not high priority - removing milestone

**Comment by misery** [comment]
http://code.qt.io/cgit/qt/qtbase.git/commit/?id=c937bbb4fe708f7f873ca630c6ff225f9a3f9ace

You need to use default "main" again and add "-Wl,-e,_qt_main_wrapper" to linker.

**Comment by ruslo** [comment]
@misery Thanks for the info, will try it

**Comment by ruslo** [comment]
Additional task: compare performance https://github.com/headupinclouds/gatherer/issues/91

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
