### ISSUE TITLE
Investigate Qt iOS camera captured data flow (CVPixelBufferRef optimization)

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#77]
Similar to https://github.com/headupinclouds/gatherer/issues/75 we can do some search of capturing process. This can be done by "grepping" `captureOutput:didOutputSampleBuffer:fromConnection:` function. Excluding `3rdparty` folder here are results:
- https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/plugins/avfoundation/camera/avfcamerarenderercontrol.mm
- https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/plugins/avfoundation/camera/avfmediaassetwriter.mm

**Comment by ruslo** [comment]
> avfcamerarenderercontrol.mm

class `AVFCaptureFramesDelegate : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>`

> avfmediaassetwriter.mm

class `AVFMediaAssetWriter : NSObject<AVCaptureVideoDataOutputSampleBufferDelegate>`

**Comment by ruslo** [comment]
`AVFMediaAssetWriter` receiving `sampleBuffer` in `captureOutput:didOutputSampleBuffer:fromConnection:`
- goes to `AVFCaptureFramesDelegate` by calling method with the same name `captureOutput:didOutputSampleBuffer:fromConnection:`
- goes to `writeVideoSampleBuffer`
  - -> `[self setStartTimeFrom:sampleBuffer]`
    - -> `CMSampleBufferGetPresentationTimeStamp(sampleBuffer)` // just read timestamp
  - -> `CMSampleBufferGetPresentationTimeStamp(sampleBuffer)` // just read timestamp
  - -> `[m_cameraWriterInput appendSampleBuffer:sampleBuffer]` // pass it to [AVAssetWriterInput](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAssetWriterInput_Class/) class that will write samples to output file

**Comment by ruslo** [comment]
`AVFCaptureFramesDelegate` receiving `sampleBuffer` in `captureOutput:didOutputSampleBuffer:fromConnection:`. That looks more interesting. It creates QVideoFrame object from sample. I guess this object is passed to us in `filter::run` method:

``` objc
- (void)captureOutput:(AVCaptureOutput *)captureOutput
         didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer
         fromConnection:(AVCaptureConnection *)connection
{
    Q_UNUSED(connection);
    Q_UNUSED(captureOutput);

    // NB: on iOS captureOutput/connection can be nil (when recording a video -
    // avfmediaassetwriter).

    CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);

    int width = CVPixelBufferGetWidth(imageBuffer);
    int height = CVPixelBufferGetHeight(imageBuffer);
    QVideoFrame::PixelFormat format =
            AVFCameraViewfinderSettingsControl2::QtPixelFormatFromCVFormat(CVPixelBufferGetPixelFormatType(imageBuffer));

    if (format == QVideoFrame::Format_Invalid)
        return;

    QVideoFrame frame(new CVPixelBufferVideoBuffer(imageBuffer), QSize(width, height), format);
    m_renderer->syncHandleViewfinderFrame(frame);
}
```

**Comment by ruslo** [comment]
Okay, looks like this is a place we need to patch:

``` cpp
// file: avfcamerarenderercontrol.mm (not header!)
class CVPixelBufferVideoBuffer : public QAbstractPlanarVideoBuffer
{
    friend class CVPixelBufferVideoBufferPrivate; // can't find this class! seems this line is useless
public:
    CVPixelBufferVideoBuffer(CVPixelBufferRef buffer)
        : QAbstractPlanarVideoBuffer(NoHandle) // NoHandle type that we are receiving
        , m_buffer(buffer) // CVPixelBufferRef saved!
        , m_mode(NotMapped)
    {
        CVPixelBufferRetain(m_buffer);
    }

    virtual ~CVPixelBufferVideoBuffer()
    {
        CVPixelBufferRelease(m_buffer);
    }

    MapMode mapMode() const { return m_mode; }

    int map(QAbstractVideoBuffer::MapMode mode, int *numBytes, int bytesPerLine[4], uchar *data[4]);
    uchar *map(MapMode mode, int *numBytes, int *bytesPerLine);
    void unmap();

private:
    CVPixelBufferRef m_buffer; // private field, so looks like QML filter fx example (issue #78) doesn't use this buffer too...
    MapMode m_mode;
};
```

What can we do:
- Move this class to some header. Need to protect it with `Q_OS_IOS`.
- Allow access to the `m_buffer`
- Pass this `CVPixelBufferRef` to OGLES library. Thats what `void* inputDataPtr` mean: https://github.com/headupinclouds/ogles_gpgpu/blob/d2b4093fc62ba5ab553e1d3f779c638ddaf1a4b0/ogles_gpgpu/platform/ios/memtransfer_ios.cpp#L133

**Comment by ruslo** [comment]
By default there is no access to `QAbstractBuffer` from `QVideoFrame`:
- https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/multimedia/video/qvideoframe.h#L49

But it used internally, so can be patched too:
- https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/multimedia/video/qvideoframe.cpp#L107

**Comment by ruslo** [comment]
I think this is the most easiest way: https://github.com/hunter-packages/Qt/commit/0a23542c107a80da7a83a01949eca384198dd7d1

**Comment by ruslo** [comment]
> I think this is the most easiest way: hunter-packages/Qt@0a23542

Looks like such approach break some internal stuff. Example doesn't work as expected even when filter is off. Will revert this change and try https://github.com/headupinclouds/gatherer/issues/80

**Comment by ruslo** [comment]
> I think this is the most easiest way: hunter-packages/Qt@0a23542

This approach looks worse but works better: https://github.com/hunter-packages/Qt/commit/0988b56be26e4a8d78fa451e589a63617683a8b6. Can be used in future to determine buffer creation overhead.

**Comment by ruslo** [comment]
For the record now using non-patched Qt version. CVPixelBuffer created manually: https://github.com/headupinclouds/gatherer/commit/5c438c3d68d3c46c14ea20ef1efe5f115e8d4ab9

I'll keep it open so we can test patched vs non-patched Qt versions performance. Priority not high -> removing milestone for now.

**Comment by headupinclouds** [comment]
This might be important again.  I'm looking at an optimization (via GPUImage) that uploads the NV21/YUV texture as a full resolution luminance (type LUMINANCE) + 1/2 resolution chrominance texture (LUMINANCE_ALPHA) followed by creation of BGRA texture in shaders.  It is all implemented, but it doesn't seem to work from a raw pointer due to a minor technical limitation.  

As reported here:
http://useranswer.com/answer/cvopenglestexturecachecreatetexturefromimage-returns-error-6683/

For some reason you cannot create a CVPixelBufferRef from a raw pointer of type kCVPixelFormatType_420YpCbCr8BiPlanarFullRange using either CVPixelBufferCreateWithPlanarBytes  or CVPixelBufferCreateWithBytes -- they both create a CVPixelBufferRef with iosurface=0x0.  You have to use CVPixelBufferCreate and memcpy the luminance and chrominance planes manually.  I will try to get this working at least, and it may still result in a net gain over BGRA input.

Also: http://stackoverflow.com/a/14514068/5724090

**Comment by headupinclouds** [comment]
Update: The above modification is now working.  It requires a `memcpy()` for the luminance and chrominance planes to create a CVPixelBufferRef in NV12 format.  This is wasteful since the original frame is already provided by iOS in this format with a valid `iosurface` attribute.

**Comment by ruslo** [comment]
>  This is wasteful since the original frame is already provided by iOS in this format with a valid iosurface attribute

So I guess we can try patched Qt version again? Need to test performance and see if it makes any difference.

**Comment by headupinclouds** [comment]
Unfortunately that seems to be the case if we want to use NV12 format directly. 

These are the additional copy calls I added of the NV12 format iOS texture cache update in memtransfer_ios.cpp:

```
                memcpy(baseAddressY, yPtr, bytesPerRow0 * bufferHeight0);
                memcpy(baseAddressUV, uvPtr, bytesPerRow1 * bufferHeight1);
```

On my iPhone 5s with the front facing camera at maximum resolution, this is adding close to 5 ms:

```
seconds: 0.00465086 bytes: 1.8432e+06
```

so it would be good to remove this for many real time applications.  The higher resolution back facing camera might be worse off. 

I haven't stepped through the internal QVideoFrame path.

@ruslo:  From your previous look at this, Do you know if Qt introduces any copies between the frame grab and the time VideoFilterRunnable::run() receives the QVideoFrame?  I recall you ran into some issues somewhere.  

If we can confirm that there are no copies, then I think adding a new designed CVPixelBufferRef pointer  (as `void *`) to the QVideoFrame might make sense.  We could submit that upstream without breaking anything.  

I see two alternatives:
1) Add the texture creation to native QT code at the time of capture  `(input->handleType() == QAbstractVideoBuffer::GLTextureHandle)` to mirror the Android behavior. 
2) Manage the iOS camera directly in objective-c++.

**Comment by headupinclouds** [comment]
Relates to #91

**Comment by ruslo** [comment]
>  I recall you ran into some issues somewhere

Issues was about adding new handle type `CVPixelBufferHandle`. I think there is some internal code that need to be patched too, like `if(handle == NoHandle) { /* do something */ }` -> `if(handle == NoHandle || handle == CVPixelBufferHandle) { /* do something */ }`

>  then I think adding a new designed CVPixelBufferRef pointer (as void *) to the QVideoFrame might make sense

Already have this version: https://github.com/hunter-packages/Qt/commit/0988b56be26e4a8d78fa451e589a63617683a8b6, works fine from what I remember

> We could submit that upstream without breaking anything

The main challenge here is not breaking old stuff but careful design. `virtual void*` with CVPixelBuffer looks badly designed but works, `CVPixelBufferHandle` looks better but require additional fixes and knowledge of Qt's structure. I think it make sense to start a discussion in some forum or in feature request bug. Results of performance measurement will be important prove of necessity of patches.

> Add the texture creation to native QT code at the time of capture (input->handleType() == QAbstractVideoBuffer::GLTextureHandle) to mirror the Android behavior

This will add additional overhead which is not needed for user who not using camera frames in GPU.

**Comment by headupinclouds** [comment]
The patch from @ruslo has been integrated and with the YUV to RGB shader the iOS qmlvideofilter sample seems to be pretty well streamlined.  Closing...
