### ISSUE TITLE
Add example: QML Video Shader Effects Example

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#78]
- http://doc.qt.io/qt-5/qtmultimedia-video-qmlvideofx-example.html
- https://github.com/hunter-packages/Qt/blob/hunter-5.5.1/qtmultimedia/examples/multimedia/video/qmlvideofx/shaders/wobble.fsh

**Comment by ruslo** [comment]
Registration of `VideoOutput` QML class: https://github.com/hunter-packages/Qt/blob/84a5846a20da62e2e2c73c1218927f8746c42de6/qtmultimedia/src/imports/multimedia/multimedia.cpp#L81

**Comment by headupinclouds** [comment]
Closing this qt specific solution in favor of the less restricted ogles_gpgpu solution
