### ISSUE TITLE
arrayfire 

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#85]
OpenCL image processing (need OpenGL to OpenCL interop first)
https://github.com/arrayfire/arrayfire
##

**Comment by ruslo** [comment]
Added: https://github.com/ruslo/hunter/wiki/pkg.arrayfire.

For now it just compiles. I've got runtime errors on both Linux and OSX. Will investigate OSX problems first.

**Comment by ruslo** [comment]
> I've got runtime errors on both Linux and OSX

This is because static libraries used, set default to shared:
- https://github.com/ruslo/hunter/commit/3cda114382550400d67f3757be35a379afb5e3dc

@headupinclouds As far as I understand ArrayFire is not designed to be used on Android or iOS, right?

**Comment by headupinclouds** [comment]
I think it will work on Android, but haven't looked int detail.  
http://arrayfire.com/getting-started-with-opencl-on-android/

It definitely won't work on iOS.

**Comment by headupinclouds** [comment]
gatherer is retired, closing.
