### ISSUE TITLE
[Qt QML iOS] Investigate CVPixelBuffer creation overhead

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#91]
~~Add fps info to target `declarative-camera`. Test performance vs [OGLES](https://github.com/headupinclouds/gatherer/issues/61) (and the GPUImage samples).~~ See #120

**Comment by headupinclouds** [comment]
Frame rate was added to qmlvideofilter.  Some profiling was done in iOS.  NV12 to BGR shaders were added to ogles_gpgpu (from GPUImage), but this currently requires a memcpy for y and uv planes on iOS. @ruslo has a patched QT version in hunter that stores the `CVPixelBuffer` pointer from the camera provided `CMSampleBuffer`.   

Should this change be submitted upstream?

The Xcode profiler should reveal any performance gaps wrt GPUImage video samples.  I expect access to the original `CVPixelBuffer` pointer should give us nearly identical performance.  As mentioned in #77 

```
For some reason you cannot create a CVPixelBufferRef from a raw pointer of type
kCVPixelFormatType_420YpCbCr8BiPlanarFullRange using either
CVPixelBufferCreateWithPlanarBytes or CVPixelBufferCreateWithBytes -- they both create a
CVPixelBufferRef with iosurface=0x0. You have to use CVPixelBufferCreate and memcpy
the luminance and chrominance planes manually.
```

**Comment by ruslo** [comment]
> Add fps info to target declarative-camera. Test performance vs OGLES (and the GPUImage samples).

I think it's not related. Moved to #120

**Comment by ruslo** [comment]
> patched QT version in hunter that stores the CVPixelBuffer pointer from the camera provided CMSampleBuffer

Just for clarification, in fact we need to compare two versions of Qt:
- Non-patched version of Qt where we need to create `CVPixelBuffer` manually and copy Y and UV planes (overhead we want to measure)
- Patched version of Qt with extra method that do return `CVPixelBuffer` to user so there is no need to copy Y and UV planes

Collect next params:
- Does FPS changes (unlikely)
- Does CPU usage changes
- Does RAM usage changes

**Comment by ruslo** [comment]
## New branch

I've created branch [cvpixelbuffer-performance](https://github.com/headupinclouds/gatherer/tree/cvpixelbuffer-performance):
- Add patched Qt version to Hunter/config.cmake
- New option `GATHERER_TEST_QT_CVPIXELBUFFER`: ON - use native CVPixelBuffer using extra method added to Qt, OFF - old behaviour with Y and UV copying
- Back camera used in testing since it has better characteristics

## Testing
- Switch to branch `cvpixelbuffer-performance`
- In both variants when Xcode project is openned pick qmlvideofilter target and set variant to Release (you can verify that mode is Release by checking that there are not so much messages in Xcode's "Debug area" as usual)
- Old version with manual CVPixelBufferRef creating and memcpy:

```
> build.py --toolchain ios-9-1-armv7 --verbose --open --config Release --clear --fwd GATHERER_TEST_QT_CVPIXELBUFFER=NO
```
- New version with using native CVPixelBufferRef:

```
> build.py --toolchain ios-9-1-armv7 --verbose --open --config Release --clear --fwd GATHERER_TEST_QT_CVPIXELBUFFER=YES
```

## Results

`qmlvideofilter` launched for 60 seconds without filtering then filter turned ON for another 60 seconds. 

# iPad2, iOS 9.1, 1280x720

Here is screenshot of launching old version with CVPixelBufferRef manual creation and copying Y and UV planes. CPU usage changed from 35-38% to 60-63%, FPS dropped from 30 to 25:

![created-cvpixelbuffer](https://cloud.githubusercontent.com/assets/4346993/12530124/61c69dbc-c206-11e5-85b0-96061f9cefb8.png)

There is almost no difference in version with native CVPixelBuffer (for some reason Xcode shows 36 FPS, Qt's widget still shows 30):

![native-cvpixelbuffer](https://cloud.githubusercontent.com/assets/4346993/12530132/adbaf3bc-c206-11e5-9a69-6b2052f0c67a.png)

# iPhone 4S, iOS 9.2, 1920x1080

Creating CVPixelBuffer manually. iPhone behaves differently. CPU usage almost haven't changed. FPS dropped from 30 to 12-14:

![created-cvpixelbuffer](https://cloud.githubusercontent.com/assets/4346993/12533440/52c68172-c262-11e5-8536-c42ba06bcdcf.png)

Using native CVPixelBuffer. This is interesting, CPU usage became lower :) Probably because FPS changed from 30 to 22-24:

![native-cvpixelbuffer](https://cloud.githubusercontent.com/assets/4346993/12533442/5b61ba54-c262-11e5-9da4-15fe6e367870.png)

Anyway all parameters (CPU, RAM, FPS) still better.

Note: best resolution is 3264x2448 but I'm receiving low memory warning so decide to switch to lower 1920x1080.

**Comment by headupinclouds** [comment]
> There is almost no difference in version with native CVPixelBuffer (for some reason Xcode shows 36 FPS, Qt's widget still shows 30):

Awesome.  Nice patch!  Let's make this the default recipe and submit this for review.

**Comment by ruslo** [comment]
> Let's make this the default recipe

https://github.com/headupinclouds/gatherer/pull/122

> submit this for review

Will take a look

**Comment by ruslo** [comment]
> > submit this for review
> 
> Will take a look

Well seems that somebody made related work already: https://codereview.qt-project.org/#/c/113458/3

Didn't noticed that because last time I've tested 5.6.0-alpha in [this bug](https://github.com/headupinclouds/gatherer/issues/76) which still has `CVPixelBufferRef`: https://github.com/hunter-packages/Qt/blob/023e0e99cceaa3a905b50fb434f5aedec12da593/qtmultimedia/src/plugins/avfoundation/camera/avfcamerarenderercontrol.mm#L130

And 5.6.0-beta was released quite in the same period of time (17 Dec): http://download.qt.io/development_releases/qt/5.6/5.6.0-beta/single/. In beta there is no `CVPixelBufferRef` anymore. Now texture name returned: https://github.com/hunter-packages/Qt/blob/da94d63d6b5151ebfab30a90daa649097b7f53bb/qtmultimedia/src/plugins/avfoundation/camera/avfcamerarenderercontrol.mm#L186

I've registered in [gerrit](https://codereview.qt-project.org/#/admin/projects/qt/qtmultimedia) so will check sources next time. Though [this patch](https://github.com/hunter-packages/Qt/commit/0988b56be26e4a8d78fa451e589a63617683a8b6) was quite trivial and now we have opportunity to compare performance of two different approaches.

Moving this part to https://github.com/headupinclouds/gatherer/issues/76.

**Comment by headupinclouds** [comment]
Interesting.  I notice that [the qt patch you found](https://github.com/hunter-packages/Qt/blob/da94d63d6b5151ebfab30a90daa649097b7f53bb/qtmultimedia/src/plugins/avfoundation/camera/avfcamerarenderercontrol.mm#L186) is using a BGRA video feed for the texture conversion.  I think having the CVPixelBufferRef as an option (`void *`) provides a lot of flexibility.   My understanding is that is not currently part of any QT branch/patch (other than your hunter version).  I'm curious if the NV12 video with GPU shader based YUV to BGRA conversion we added (via GPUImage) comes out ahead in any cases/platforms/resolutions.  Perhaps that would be most noticeable with higher resolutions due to the more compact NV12 format.

**Comment by headupinclouds** [comment]
@ruslo: your patch is working well and i like the current CVPixelBufferRef approach.  i'm closing this for the milestone and we can create a separate issue for patch follow ups.  i see two options moving forward:

1) apply your hunter CVPixelBufferRef patch upstream since it shouldn't impact any existing code and there is a good argument that this provides important flexibility (yuv to bgra)
1.5) apply the minimal patch locally in hunter for subsequent releases (not ideal, but doable)
2) adopt the BGRA based texture cache in 5.6.0-beta and lose the yuv->bgra shader optimizations when using gatherer QT applications
2.5) submit the yuv to bgra shader optimization upstream (would need additional benchmarking efforts demonstrating a benefit).
