### ISSUE TITLE
No filter applied to qmlvideofilter when USE_OGLES_GPGPU=OFF 

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#93]
Update needed here: https://github.com/headupinclouds/gatherer/blob/05900d2576814bba78ad2ac6700f73f356ec0be1/src/app/qmlvideofilter/VideoFilterRunnable.cpp#L280

**Comment by ruslo** [comment]
@headupinclouds On second thought does option `USE_OGLES_GPGPU` needed now? I mean let it be `ON` by default (?)

**Comment by headupinclouds** [comment]
Yeah, I don't see a need to support both paths.

**Comment by ruslo** [comment]
Removed: https://github.com/headupinclouds/gatherer/pull/95
