### ISSUE TITLE
Cleanup target

### ISSUE THREAD

**Issue by ruslo** [headupinclouds/gatherer#97]
Some targets not needed now because Qt QML + OGLES works fine.
- Remove targets
- Cleanup table: https://github.com/headupinclouds/gatherer/wiki/Status

**Comment by headupinclouds** [comment]
Most of these were stepping stones that lead to qmlvideofilter.

KEEP:
qmlvideofilter: QML/QT + ogles_gpgpu processing YES
ogles_gpgpu_test: simple concise glfw + cv::VideoCapture sample, useful for testing without long QT builds  YES
OGLESGPGPUVideoCam: This is part of ogles_gpgpu, YES

UNSURE:
declarative-camera:  ??? maybe

DELETE:
camera_test: basic cv::VideoCamera unit test, NO
preview: gatherer:graphics + glfw sample NO
qt-camera: non qml camera example, not ios/android friendly, NO
preview-qt: QT + ogles_gpgpu, not ios/android friendly, replaced by qmlvideofilter NO
opencv-qt-video: C++ QT sample for drawing frames from cv::VideoCapture NO

**Comment by ruslo** [comment]
Table updated: https://github.com/headupinclouds/gatherer/wiki/Status
