### ISSUE TITLE
qmlvideofilter runtime error (libcxx, QtCopyQmlTo)

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/gatherer#99]
In the latest `videofilter` branch the `qmlvideofilter` target is building, but QT is reporting some problems at runtime.  Launching the target `_builds/libcxx-Release/src/app/qmlvideofilter/qmlvideofilter`

results in this

```
qrc:///main.qml:36:1: module "QtMultimedia" is not installed
qrc:///main.qml:35:1: module "QtQuick" is not installed
qrc:///main.qml:36:1: module "QtMultimedia" is not installed
qrc:///main.qml:35:1: module "QtQuick" is not installed
```

@ruslo : Any thoughts?  I'll see what I can glean from the other examples.  Also #55

**Comment by headupinclouds** [comment]
I'm probably missing some background on this.  

I notice this states GUI applications must be run from a bundle.

http://doc.qt.io/qt-5/osx-deployment.html

"On OS X, a GUI application must be built and run from a bundle, which is a directory structure that appears as a single entity when viewed in the Finder. A bundle for an application typically contains the executable and all the resources it needs. Here is the snapshot of an application bundle structure:"

Update: Using a bundle + Xcode build produces similar errors.

**Comment by headupinclouds** [comment]
More diagnostic info using QT_DEBUG_PLUGINS hint from here https://github.com/ruslo/hunter/wiki/pkg.qt

```
export QT_DEBUG_PLUGINS=1
indra-234:gatherer dhirvonen$ _builds/libcxx-Release/src/app/qmlvideofilter/qmlvideofilter 
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3" since plugins are disabled in static builds
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1" since plugins are disabled in static builds
qrc:///main.qml:35:1: module "QtQuick" is not installed
qrc:///main.qml:36:1: module "QtMultimedia" is not installed
qrc:///main.qml:35:1: module "QtQuick" is not installed
qrc:///main.qml:36:1: module "QtMultimedia" is not installed
```

**Comment by headupinclouds** [comment]
Moving this into `if(GATHERER_OPENGL_ES)` for now

**Comment by ruslo** [comment]
QML files need to be copied to the location where they can be found by application executable. I haven't debug this stuff for libcxx/xcode toolchain: https://github.com/hunter-packages/QtQmlManager/blob/master/cmake/QtCopyQmlTo.cmake

**Comment by ruslo** [comment]
> QML files need to be copied to the location where they can be found by application executable

Doesn't help, there is an openned bug: https://bugreports.qt.io/browse/QTBUG-35754. Workaround works for me with simple example, will check if it can be applied to qmlvideofilter.

**Comment by ruslo** [comment]
Compile/link errors fixed for OSX toolchain.

Now got runtime error in ogles_gpgpu:

```
GL_VENDOR: Intel Inc.
ogles_gpgpu::Core - reset - resetting core
ogles_gpgpu::Core - reset - resetting core
ogles_gpgpu::Core - addProcToPipeline - adding processor #1 to pipeline
ogles_gpgpu::Core - addProcToPipeline - adding processor #2 to pipeline
ogles_gpgpu::Core - checkGLExtensions - NPOT mipmaps support: 0
ogles_gpgpu::Core - checkGLErr - init OpenGL - GL error '1282' occured
```

I guess ogles_gpgpu support only OpenGL ES, not OpenGL?

**Comment by headupinclouds** [comment]
I patched it a few months ago so that it would work in OS X.  There were glfw + ogles_gpgpu samples that were working in OS X.  I may have broken those with some changes recently.  Can get some simple regression tests at some point.

**Comment by ruslo** [comment]
Error after this call: https://github.com/headupinclouds/gatherer/blob/51ffbf00363b92de0f38fb78c1ac67a0396db00f/src/app/qmlvideofilter/VideoFilterRunnable.cpp#L105

```
GL_INVALID_OPERATION: The specified operation is not allowed in the current state.
```

According to [documentation](https://www.opengl.org/sdk/docs/man/) `glGetRenderbufferParameteriv` generate `GL_INVALID_OPERATION` when buffer is not bound:

```
GL_INVALID_OPERATION is generated by glGetRenderbufferParameteriv if zero is bound to target. 
```

**Comment by headupinclouds** [comment]
I've added a few fixes and OS X functionality is now working (as of #125) after your installation fixes above.  Thanks!  Closing...
